/*
 * Hathora Cloud API
 *
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateUserInvite
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateUserInviteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateUserInvite
        //private CreateUserInvite instance;

        public CreateUserInviteTests()
        {
            // TODO uncomment below to create an instance of CreateUserInvite
            //instance = new CreateUserInvite();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateUserInvite
        /// </summary>
        [Test]
        public void CreateUserInviteInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateUserInvite
            //Assert.IsType<CreateUserInvite>(instance);
        }

        /// <summary>
        /// Test the property 'UserEmail'
        /// </summary>
        [Test]
        public void UserEmailTest()
        {
            // TODO unit test for the property 'UserEmail'
        }
    }
}
