/*
 * Hathora Cloud API
 *
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hathora.Cloud.Sdk.Api;
using Hathora.Cloud.Sdk.Model;
using Hathora.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Hathora.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LobbyVisibility
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LobbyVisibilityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LobbyVisibility
        //private LobbyVisibility instance;

        public LobbyVisibilityTests()
        {
            // TODO uncomment below to create an instance of LobbyVisibility
            //instance = new LobbyVisibility();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LobbyVisibility
        /// </summary>
        [Test]
        public void LobbyVisibilityInstanceTest()
        {
            // TODO uncomment below to test "IsType" LobbyVisibility
            //Assert.IsType<LobbyVisibility>(instance);
        }

    }
}
