/*
 * Hathora Cloud API
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hathora.client.api;

import com.hathora.client.ApiException;
import com.hathora.client.model.ApiError;
import com.hathora.client.model.AppConfig;
import com.hathora.client.model.Application;
import com.hathora.client.model.ApplicationWithDeployment;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppV1Api
 */
@Disabled
public class AppV1ApiTest {

    private final AppV1Api api = new AppV1Api();

    /**
     * Create a new [application](https://hathora.dev/docs/concepts/hathora-entities#application).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAppTest() throws ApiException {
        AppConfig appConfig = null;
        Application response = api.createApp(appConfig);
        // TODO: test validations
    }

    /**
     * Delete an [application](https://hathora.dev/docs/concepts/hathora-entities#application) using &#x60;appId&#x60;. Your organization will lose access to this application.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAppTest() throws ApiException {
        String appId = null;
        api.deleteApp(appId);
        // TODO: test validations
    }

    /**
     * Get details for an [application](https://hathora.dev/docs/concepts/hathora-entities#application) using &#x60;appId&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAppInfoTest() throws ApiException {
        String appId = null;
        Application response = api.getAppInfo(appId);
        // TODO: test validations
    }

    /**
     * Returns an unsorted list of your organization’s [applications](https://hathora.dev/docs/concepts/hathora-entities#application). An application is uniquely identified by an &#x60;appId&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAppsTest() throws ApiException {
        List<ApplicationWithDeployment> response = api.getApps();
        // TODO: test validations
    }

    /**
     * Update data for an existing [application](https://hathora.dev/docs/concepts/hathora-entities#application) using &#x60;appId&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAppTest() throws ApiException {
        String appId = null;
        AppConfig appConfig = null;
        Application response = api.updateApp(appId, appConfig);
        // TODO: test validations
    }

}
