/*
 * Hathora Cloud API
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hathora.client.api;

import com.hathora.client.ApiException;
import com.hathora.client.model.ApiError;
import com.hathora.client.model.CreateLobbyV3Params;
import com.hathora.client.model.LobbyV3;
import com.hathora.client.model.Region;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LobbyV3Api
 */
@Disabled
public class LobbyV3ApiTest {

    private final LobbyV3Api api = new LobbyV3Api();

    /**
     * Create a new lobby for an [application](https://hathora.dev/docs/concepts/hathora-entities#application). A lobby object is a wrapper around a [room](https://hathora.dev/docs/concepts/hathora-entities#room) object. With a lobby, you get additional functionality like configuring the visibility of the room, managing the state of a match, and retrieving a list of public lobbies to display to players.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createLobbyTest() throws ApiException {
        String appId = null;
        CreateLobbyV3Params createLobbyV3Params = null;
        String shortCode = null;
        String roomId = null;
        LobbyV3 response = api.createLobby(appId, createLobbyV3Params, shortCode, roomId);
        // TODO: test validations
    }

    /**
     * Get details for a lobby.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLobbyInfoByRoomIdTest() throws ApiException {
        String appId = null;
        String roomId = null;
        LobbyV3 response = api.getLobbyInfoByRoomId(appId, roomId);
        // TODO: test validations
    }

    /**
     * Get details for a lobby. If 2 or more lobbies have the same &#x60;shortCode&#x60;, then the most recently created lobby will be returned.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLobbyInfoByShortCodeTest() throws ApiException {
        String appId = null;
        String shortCode = null;
        LobbyV3 response = api.getLobbyInfoByShortCode(appId, shortCode);
        // TODO: test validations
    }

    /**
     * Get all active lobbies for a given [application](https://hathora.dev/docs/concepts/hathora-entities#application). Filter the array by optionally passing in a &#x60;region&#x60;. Use this endpoint to display all public lobbies that a player can join in the game client.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listActivePublicLobbiesTest() throws ApiException {
        String appId = null;
        Region region = null;
        List<LobbyV3> response = api.listActivePublicLobbies(appId, region);
        // TODO: test validations
    }

}
