/*
 * Hathora Cloud API
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hathora.client.api;

import com.hathora.client.ApiException;
import com.hathora.client.model.ApiError;
import com.hathora.client.model.MetricName;
import com.hathora.client.model.RecordPartialMetricNameMetricValueArray;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MetricsV1Api
 */
@Disabled
public class MetricsV1ApiTest {

    private final MetricsV1Api api = new MetricsV1Api();

    /**
     * Get metrics for a [process](https://hathora.dev/docs/concepts/hathora-entities#process) using &#x60;appId&#x60; and &#x60;processId&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMetricsTest() throws ApiException {
        String appId = null;
        String processId = null;
        List<MetricName> metrics = null;
        Double end = null;
        Double start = null;
        Integer step = null;
        RecordPartialMetricNameMetricValueArray response = api.getMetrics(appId, processId, metrics, end, start, step);
        // TODO: test validations
    }

}
