/* tslint:disable */
/* eslint-disable */
/**
 * Hathora Cloud API
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LobbyVisibility } from './LobbyVisibility';
import {
    LobbyVisibilityFromJSON,
    LobbyVisibilityFromJSONTyped,
    LobbyVisibilityToJSON,
} from './LobbyVisibility';
import type { Region } from './Region';
import {
    RegionFromJSON,
    RegionFromJSONTyped,
    RegionToJSON,
} from './Region';

/**
 * 
 * @export
 * @interface CreateLobbyParams
 */
export interface CreateLobbyParams {
    /**
     * 
     * @type {LobbyVisibility}
     * @memberof CreateLobbyParams
     */
    visibility: LobbyVisibility;
    /**
     * User input to initialize the game state. Object must be smaller than 64KB.
     * @type {object}
     * @memberof CreateLobbyParams
     */
    initialConfig: object;
    /**
     * 
     * @type {Region}
     * @memberof CreateLobbyParams
     */
    region: Region;
}

/**
 * Check if a given object implements the CreateLobbyParams interface.
 */
export function instanceOfCreateLobbyParams(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "visibility" in value;
    isInstance = isInstance && "initialConfig" in value;
    isInstance = isInstance && "region" in value;

    return isInstance;
}

export function CreateLobbyParamsFromJSON(json: any): CreateLobbyParams {
    return CreateLobbyParamsFromJSONTyped(json, false);
}

export function CreateLobbyParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLobbyParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visibility': LobbyVisibilityFromJSON(json['visibility']),
        'initialConfig': json['initialConfig'],
        'region': RegionFromJSON(json['region']),
    };
}

export function CreateLobbyParamsToJSON(value?: CreateLobbyParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visibility': LobbyVisibilityToJSON(value.visibility),
        'initialConfig': value.initialConfig,
        'region': RegionToJSON(value.region),
    };
}

