/*
 * Hathora Cloud API
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hathora.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hathora.client.model.ExposedPort;
import com.hathora.client.model.ProcessStatus;
import com.hathora.client.model.Region;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.hathora.client.JSON;

/**
 * ProcessV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProcessV2 {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ProcessStatus status;

  public static final String SERIALIZED_NAME_ROOMS_ALLOCATED = "roomsAllocated";
  @SerializedName(SERIALIZED_NAME_ROOMS_ALLOCATED)
  private Integer roomsAllocated;

  public static final String SERIALIZED_NAME_TERMINATED_AT = "terminatedAt";
  @SerializedName(SERIALIZED_NAME_TERMINATED_AT)
  private OffsetDateTime terminatedAt;

  public static final String SERIALIZED_NAME_STOPPING_AT = "stoppingAt";
  @SerializedName(SERIALIZED_NAME_STOPPING_AT)
  private OffsetDateTime stoppingAt;

  public static final String SERIALIZED_NAME_STARTED_AT = "startedAt";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  private OffsetDateTime startedAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_ROOMS_PER_PROCESS = "roomsPerProcess";
  @SerializedName(SERIALIZED_NAME_ROOMS_PER_PROCESS)
  private Integer roomsPerProcess;

  public static final String SERIALIZED_NAME_ADDITIONAL_EXPOSED_PORTS = "additionalExposedPorts";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_EXPOSED_PORTS)
  private List<ExposedPort> additionalExposedPorts = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPOSED_PORT = "exposedPort";
  @SerializedName(SERIALIZED_NAME_EXPOSED_PORT)
  private ExposedPort exposedPort;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private Region region;

  public static final String SERIALIZED_NAME_PROCESS_ID = "processId";
  @SerializedName(SERIALIZED_NAME_PROCESS_ID)
  private String processId;

  public static final String SERIALIZED_NAME_DEPLOYMENT_ID = "deploymentId";
  @SerializedName(SERIALIZED_NAME_DEPLOYMENT_ID)
  private Integer deploymentId;

  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public ProcessV2() {
  }

  public ProcessV2 status(ProcessStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull

  public ProcessStatus getStatus() {
    return status;
  }


  public void setStatus(ProcessStatus status) {
    this.status = status;
  }


  public ProcessV2 roomsAllocated(Integer roomsAllocated) {
    
    this.roomsAllocated = roomsAllocated;
    return this;
  }

   /**
   * Tracks the number of rooms that have been allocated to the process.
   * @return roomsAllocated
  **/
  @javax.annotation.Nonnull

  public Integer getRoomsAllocated() {
    return roomsAllocated;
  }


  public void setRoomsAllocated(Integer roomsAllocated) {
    this.roomsAllocated = roomsAllocated;
  }


  public ProcessV2 terminatedAt(OffsetDateTime terminatedAt) {
    
    this.terminatedAt = terminatedAt;
    return this;
  }

   /**
   * When the process has been terminated.
   * @return terminatedAt
  **/
  @javax.annotation.Nullable

  public OffsetDateTime getTerminatedAt() {
    return terminatedAt;
  }


  public void setTerminatedAt(OffsetDateTime terminatedAt) {
    this.terminatedAt = terminatedAt;
  }


  public ProcessV2 stoppingAt(OffsetDateTime stoppingAt) {
    
    this.stoppingAt = stoppingAt;
    return this;
  }

   /**
   * When the process is issued to stop. We use this to determine when we should stop billing.
   * @return stoppingAt
  **/
  @javax.annotation.Nullable

  public OffsetDateTime getStoppingAt() {
    return stoppingAt;
  }


  public void setStoppingAt(OffsetDateTime stoppingAt) {
    this.stoppingAt = stoppingAt;
  }


  public ProcessV2 startedAt(OffsetDateTime startedAt) {
    
    this.startedAt = startedAt;
    return this;
  }

   /**
   * When the process bound to the specified port. We use this to determine when we should start billing.
   * @return startedAt
  **/
  @javax.annotation.Nullable

  public OffsetDateTime getStartedAt() {
    return startedAt;
  }


  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }


  public ProcessV2 createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * When the process started being provisioned.
   * @return createdAt
  **/
  @javax.annotation.Nonnull

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ProcessV2 roomsPerProcess(Integer roomsPerProcess) {
    
    this.roomsPerProcess = roomsPerProcess;
    return this;
  }

   /**
   * Governs how many [rooms](https://hathora.dev/docs/concepts/hathora-entities#room) can be scheduled in a process.
   * minimum: 1
   * maximum: 10000
   * @return roomsPerProcess
  **/
  @javax.annotation.Nonnull

  public Integer getRoomsPerProcess() {
    return roomsPerProcess;
  }


  public void setRoomsPerProcess(Integer roomsPerProcess) {
    this.roomsPerProcess = roomsPerProcess;
  }


  public ProcessV2 additionalExposedPorts(List<ExposedPort> additionalExposedPorts) {
    
    this.additionalExposedPorts = additionalExposedPorts;
    return this;
  }

  public ProcessV2 addAdditionalExposedPortsItem(ExposedPort additionalExposedPortsItem) {
    if (this.additionalExposedPorts == null) {
      this.additionalExposedPorts = new ArrayList<>();
    }
    this.additionalExposedPorts.add(additionalExposedPortsItem);
    return this;
  }

   /**
   * Get additionalExposedPorts
   * @return additionalExposedPorts
  **/
  @javax.annotation.Nonnull

  public List<ExposedPort> getAdditionalExposedPorts() {
    return additionalExposedPorts;
  }


  public void setAdditionalExposedPorts(List<ExposedPort> additionalExposedPorts) {
    this.additionalExposedPorts = additionalExposedPorts;
  }


  public ProcessV2 exposedPort(ExposedPort exposedPort) {
    
    this.exposedPort = exposedPort;
    return this;
  }

   /**
   * Get exposedPort
   * @return exposedPort
  **/
  @javax.annotation.Nullable

  public ExposedPort getExposedPort() {
    return exposedPort;
  }


  public void setExposedPort(ExposedPort exposedPort) {
    this.exposedPort = exposedPort;
  }


  public ProcessV2 region(Region region) {
    
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @javax.annotation.Nonnull

  public Region getRegion() {
    return region;
  }


  public void setRegion(Region region) {
    this.region = region;
  }


  public ProcessV2 processId(String processId) {
    
    this.processId = processId;
    return this;
  }

   /**
   * System generated unique identifier to a runtime instance of your game server.
   * @return processId
  **/
  @javax.annotation.Nonnull

  public String getProcessId() {
    return processId;
  }


  public void setProcessId(String processId) {
    this.processId = processId;
  }


  public ProcessV2 deploymentId(Integer deploymentId) {
    
    this.deploymentId = deploymentId;
    return this;
  }

   /**
   * System generated id for a deployment. Increments by 1.
   * @return deploymentId
  **/
  @javax.annotation.Nonnull

  public Integer getDeploymentId() {
    return deploymentId;
  }


  public void setDeploymentId(Integer deploymentId) {
    this.deploymentId = deploymentId;
  }


  public ProcessV2 appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * System generated unique identifier for an application.
   * @return appId
  **/
  @javax.annotation.Nonnull

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProcessV2 instance itself
   */
  public ProcessV2 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessV2 processV2 = (ProcessV2) o;
    return Objects.equals(this.status, processV2.status) &&
        Objects.equals(this.roomsAllocated, processV2.roomsAllocated) &&
        Objects.equals(this.terminatedAt, processV2.terminatedAt) &&
        Objects.equals(this.stoppingAt, processV2.stoppingAt) &&
        Objects.equals(this.startedAt, processV2.startedAt) &&
        Objects.equals(this.createdAt, processV2.createdAt) &&
        Objects.equals(this.roomsPerProcess, processV2.roomsPerProcess) &&
        Objects.equals(this.additionalExposedPorts, processV2.additionalExposedPorts) &&
        Objects.equals(this.exposedPort, processV2.exposedPort) &&
        Objects.equals(this.region, processV2.region) &&
        Objects.equals(this.processId, processV2.processId) &&
        Objects.equals(this.deploymentId, processV2.deploymentId) &&
        Objects.equals(this.appId, processV2.appId)&&
        Objects.equals(this.additionalProperties, processV2.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, roomsAllocated, terminatedAt, stoppingAt, startedAt, createdAt, roomsPerProcess, additionalExposedPorts, exposedPort, region, processId, deploymentId, appId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessV2 {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    roomsAllocated: ").append(toIndentedString(roomsAllocated)).append("\n");
    sb.append("    terminatedAt: ").append(toIndentedString(terminatedAt)).append("\n");
    sb.append("    stoppingAt: ").append(toIndentedString(stoppingAt)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    roomsPerProcess: ").append(toIndentedString(roomsPerProcess)).append("\n");
    sb.append("    additionalExposedPorts: ").append(toIndentedString(additionalExposedPorts)).append("\n");
    sb.append("    exposedPort: ").append(toIndentedString(exposedPort)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    processId: ").append(toIndentedString(processId)).append("\n");
    sb.append("    deploymentId: ").append(toIndentedString(deploymentId)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("roomsAllocated");
    openapiFields.add("terminatedAt");
    openapiFields.add("stoppingAt");
    openapiFields.add("startedAt");
    openapiFields.add("createdAt");
    openapiFields.add("roomsPerProcess");
    openapiFields.add("additionalExposedPorts");
    openapiFields.add("exposedPort");
    openapiFields.add("region");
    openapiFields.add("processId");
    openapiFields.add("deploymentId");
    openapiFields.add("appId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("roomsAllocated");
    openapiRequiredFields.add("terminatedAt");
    openapiRequiredFields.add("stoppingAt");
    openapiRequiredFields.add("startedAt");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("roomsPerProcess");
    openapiRequiredFields.add("additionalExposedPorts");
    openapiRequiredFields.add("region");
    openapiRequiredFields.add("processId");
    openapiRequiredFields.add("deploymentId");
    openapiRequiredFields.add("appId");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProcessV2
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProcessV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProcessV2 is not found in the empty JSON string", ProcessV2.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProcessV2.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("additionalExposedPorts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `additionalExposedPorts` to be an array in the JSON string but got `%s`", jsonObj.get("additionalExposedPorts").toString()));
      }

      JsonArray jsonArrayadditionalExposedPorts = jsonObj.getAsJsonArray("additionalExposedPorts");
      // validate the required field `additionalExposedPorts` (array)
      for (int i = 0; i < jsonArrayadditionalExposedPorts.size(); i++) {
        ExposedPort.validateJsonObject(jsonArrayadditionalExposedPorts.get(i).getAsJsonObject());
      };
      // validate the optional field `exposedPort`
      if (jsonObj.get("exposedPort") != null && !jsonObj.get("exposedPort").isJsonNull()) {
        ExposedPort.validateJsonObject(jsonObj.getAsJsonObject("exposedPort"));
      }
      if (!jsonObj.get("processId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `processId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("processId").toString()));
      }
      if (!jsonObj.get("appId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProcessV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProcessV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProcessV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProcessV2.class));

       return (TypeAdapter<T>) new TypeAdapter<ProcessV2>() {
           @Override
           public void write(JsonWriter out, ProcessV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProcessV2 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProcessV2 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProcessV2 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProcessV2
  * @throws IOException if the JSON string is invalid with respect to ProcessV2
  */
  public static ProcessV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProcessV2.class);
  }

 /**
  * Convert an instance of ProcessV2 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

