/*
 * Hathora Cloud API
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hathora.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ProcessStatus
 */
@JsonAdapter(ProcessStatus.Adapter.class)
public enum ProcessStatus {
  
  STARTING("starting"),
  
  RUNNING("running"),
  
  DRAINING("draining"),
  
  STOPPING("stopping"),
  
  STOPPED("stopped"),
  
  FAILED("failed");

  private String value;

  ProcessStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProcessStatus fromValue(String value) {
    for (ProcessStatus b : ProcessStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ProcessStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProcessStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ProcessStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ProcessStatus.fromValue(value);
    }
  }
}

