/*
 * Hathora Cloud API
 * Welcome to the Hathora Cloud API documentation! Learn how to use the Hathora Cloud APIs to build and scale your game servers globally.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hathora.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RoomReadyStatus
 */
@JsonAdapter(RoomReadyStatus.Adapter.class)
public enum RoomReadyStatus {
  
  ACTIVE("active"),
  
  STARTING("starting");

  private String value;

  RoomReadyStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RoomReadyStatus fromValue(String value) {
    for (RoomReadyStatus b : RoomReadyStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RoomReadyStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final RoomReadyStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RoomReadyStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RoomReadyStatus.fromValue(value);
    }
  }
}

